# Assignment instruction

NAME: Akitaka Matsuo

In this part of the assignment, you are asked to answer questions about basics of python and NumPy. Answer all questions. This assignment comprises 40 percent of the assignment grade.


In [ ]:
import numpy as np

# Python introduction (15 points)

Split the following string by word and create a list

In [ ]:
string = "A driverless truck is ready to start earning a living"

For the python list below, run a loop where the number will be printed out when it is greater than 15. The output should look like:
```
17
18
17
18
18
18
16
17
16
```

In [ ]:
list_x = [ 0,  4, 17, 15, 10, 13,  7, 15, 13, 18,  3,  8, 17,  3,  4, 18, 15,
        0, 13, 10, 18, 18,  9, 11,  7, 16,  8,  8, 17, 10,  1,  1, 13,  7,
       15, 11,  2,  0, 16, 15,  0,  4,  2,  0,  4, 15, 14,  7, 14,  1]

Define a funtion `inList` with following specs.

- Takes two argments:
  - `x`: a scaler
  - `l`: a list
- The function will check whether `x` exists in the list, and print out the results
  - if exists: `value is in the list`
  - if not: `value is not in the list`

For example:

```
inList(x = 3, l = [10,4,5,3])
```

Will produce

```
3 is in the list
```

# Numpy (25 points)

## Array construction

Construct following NumPy arrays (without using `array()` method)

- one dimensional arrays:
    1. a sequece of integers from `-5` to `7`
    2. 10 random numbers drawn from uniform distribution 
    3. a decreasing sequence of integers from `23` to `0`
- two dimensional arrays:
    1. 7 x 5 random array drawn from normal distribution
    2. 2 x 7 array of zeros
    3. 3 x 4 array of 7s, like this
      ```
      array([[7., 7., 7., 7.],
             [7., 7., 7., 7.],
             [7., 7., 7., 7.]])
      ```


## Array indexing and selection

### One dimension



#### From the array below, crate a replicating matrix

In [ ]:
arr_1d = np.arange(1, 16)

(1) `array([1, 2, 3, 4, 5, 6, 7])`

(2) `array([13, 14, 15])`

#### Do the following 

1. Set the seed to `208320`
2. Construct an array with 20 random numbers from normal distribution
3. Select positive elements from the array

### Two dimension


#### From the array below, crate a replicating matrix

In [ ]:
arr_2d = np.arange(31, 61).reshape(5, 6)

(1) 
```
array([[31, 32, 33, 34, 35, 36],
       [37, 38, 39, 40, 41, 42],
       [43, 44, 45, 46, 47, 48]])
```

(2) 
```
array([[39, 40, 41],
       [45, 46, 47],
       [51, 52, 53]])
```

(3)
```
array([[43, 47],
      [55, 59]])
```

## Array operations

For the two dimensional array below, carry out the following operations

In [ ]:
arr_op = np.array([[63, 14, 95, 12, 37, 97, 51],
                  [29,  4, 69, 13, 74, 74, 32],
                  [14, 63, 83, 52, 16, 86, 78],
                  [75, 87,  2,  8, 83,  8, 32],
                  [99,  1, 66, 12, 36, 18, 76],
                  [45, 81, 23, 54, 38, 26, 30],
                  [67, 58, 79, 31, 52, 19, 76],
                  [82, 28, 34, 66, 67, 45, 32]])

(1) calculate the sum of the entire array

(2) calculate the mean of each row

(3) calculate the standard deviaiton of each column